# Generated by Django 3.0.4 on 2020-05-28 07:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('turf_booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 28, 7, 22, 56, 390865, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slot',
            name='timing',
            field=models.TimeField(default=datetime.datetime(2020, 5, 28, 7, 22, 15, 778886, tzinfo=utc)),
        ),
    ]
